### ISSUE TITLE
R. Danny doesnt pick up a star

### ISSUE THREAD

**Issue by Nyameliaaaa** [Rapptz/RoboDanny#59]

**Comment by Rapptz** [comment]
This is unlikely.

I think one of the biggest issues with the bot is when using the reaction interface there is no feedback to the user on why their star failed. I have a few ideas in mind on how to give the user feedback on failure since it's essentially suppressed such as removing the reaction or sending a DM/message on failure. I do wish we had ephemeral messages to make the latter prettier and less spammy.

Anyway as for why a star can seem like it's not being "picked up" you have the following array of reasons:

1. You are starring your own post. Self-stars aren't allowed.
2. You are doing it in a NSFW channel and the starboard channel isn't marked NSFW.
3. The channel or server has the `star` command ignored via `?config disable #channel star`
4. The starboard is locked (`?star lock` and `?star unlock`)
5. There is no starboard set up (`?starboard`)
6. The bot doesn't have permissions to send messages in the starboard for an odd reason.
7. The message is an embed-only message (it cannot be represented since the bot uses embeds to format it).
8. The message is too old (`?star age`)
9. You've been blocked by the bot either globally by me (unlikely) or in the server by the server admins.
10. The bot was down during the time period that you starred it.

**Comment by tomlin7** [comment]
![image](https://user-images.githubusercontent.com/70792552/101453293-20c95180-3955-11eb-84a9-82ee74a438b5.png)

- i'm starring someone elses post
![image](https://user-images.githubusercontent.com/70792552/101453369-3dfe2000-3955-11eb-963a-83d32c78d772.png)
- it is not an nsfw channel
![image](https://user-images.githubusercontent.com/70792552/101453459-61c16600-3955-11eb-97b8-2e1b4870e334.png)
- the star is enabled 
![image](https://user-images.githubusercontent.com/70792552/101453547-84537f00-3955-11eb-80ba-b2c63e5c6cbb.png)
- it is unlocked, still not working
![image](https://user-images.githubusercontent.com/70792552/101453599-9c2b0300-3955-11eb-9b81-5dd4d58dd4b3.png)
- there is a starboard, bot itself created it on my command
![image](https://user-images.githubusercontent.com/70792552/101454023-4efb6100-3956-11eb-8090-5ffe0d554007.png)

- the bot has permissions on this channel
![image](https://user-images.githubusercontent.com/70792552/101453759-da282700-3955-11eb-8dae-e956a859e2ff.png)
- message is plain text
- he just sent it now
- i'm hosting it, so i'm not blocked, neither he is able to star my messages, he is not in the api server too
- bot was up during that time

**Still, it is not starring messages**
